/**
 * Created by kh.levon98 on 13-Sep-16.
 */
import angular from 'angular/index';
import './helpers';

// Import our app config files
import constants  from './config/app.constants';
import appConfig  from './config/app.config';
import appRun     from './config/app.run';

// Import our dependencies
import 'angular-cookies/angular-cookies.min';
import 'angular-sanitize/angular-sanitize.min';
import 'angular-event-emitter/angular-event-emitter';
import 'angular-messages/angular-messages.min';

import 're-tree/re-tree.min';
import 'ng-device-detector/ng-device-detector.min';
import 'lodash/lodash.min';

import 'angular-ui-router/release/angular-ui-router.min';
import 'angular-storage/dist/angular-storage.min';

import 'restangular/dist/restangular.min';
import 'angular-ui-bootstrap/dist/ui-bootstrap-tpls';

// Import our templates file (generated by Gulp)
import './config/app.templates';
// Import our app functionality
import filtersModule from './filters/index';
import servicesModule from './services/index';
import componentsModule from './components/index';
import layoutsModule from './layout/index';
import pagesModule from './pages/index';

// Create and bootstrap application
const requires = [
  // project templates
  'templates',

  //
  'ngCookies',
  'ngSanitize',
  'ngEventEmitter',
  'ngMessages',
  'ng.deviceDetector',
  //
  'angular-storage',
  'ui.router',
  'restangular',
  //
  'ui.bootstrap',
  // project modules
  filtersModule,
  servicesModule,
  componentsModule,
  layoutsModule,
  pagesModule
];

// Mount on window for testing
const app = angular.module('app', requires);

angular.module('app').constant('AppConstants', constants);

angular.module('app').config(appConfig);

angular.module('app').run(appRun);

angular.bootstrap(document, ['app'], {
  strictDi: true
});
